### ISSUE TITLE
Contrast for Item Recognition Task

### ISSUE THREAD

**Issue by ferponcem** [hbp-brain-charting/public_analysis_code#19]
The `Item Recognition` task has 14 conditions, but for the 3 contrasts defined [here](https://github.com/hbp-brain-charting/public_analysis_code/blob/003a0df00238949f8b1529dfde568edc7d96e6bd/ibc_public/utils_contrasts.py#L611) only 6 are being taken into account.

Maybe we would need to remove some conditions, or maybe check if we defined the contrasts correctly.

**Comment by bthirion** [comment]
To be discussed during our meting on Tuesday evening.

**Comment by ferponcem** [comment]
After the discussion we decided to add 3 more contrasts: `prob-arrow`, `encode` and `arrow_left-arrow_right`.

* I updated the utils_contrast.py script on the [item_recognition](https://github.com/hbp-brain-charting/public_analysis_code/blob/9df11f8e3665541c2c1b6086af42a3c6e573ff7a/ibc_public/utils_contrasts.py#L660) to add those new contrasts. @bthirion I tried to be consistent, it would be great if you can have a look.

* Updated the [csv file](https://github.com/hbp-brain-charting/public_analysis_code/blob/feature/contrasts_descriptions/ibc_data/contrasts/ItemRecognition.csv) where we define the contrast.

* Updated the [documentation](https://github.com/hbp-brain-charting/admin/blob/1a746b93aa2f808743d952d64e5062e1f1bc2475/documentation/documentation.tex#L5651) with these changes as well.

Please let me know what you think.

**Comment by bthirion** [comment]
LGTM thx !
