### ISSUE TITLE
cognitive_atlas.csv does not exist

### ISSUE THREAD

**Issue by alpinho** [hbp-brain-charting/public_analysis_code#6]
This file is not available anymore and it will generate an OSERROR [in line 174 of global_stat.py](https://github.com/hbp-brain-charting/public_analysis_code/blob/8a976f9e5e6f71ef7d868899075d8556b1e52cf2/data_paper_scripts/global_stat.py#L174)

**Comment by bthirion** [comment]
The file can be found in the high_level_analysis_script folder.

**Comment by alpinho** [comment]
OK. Thanks. But this folder is in another repository. We can copy it to [data_paper_scripts](https://github.com/hbp-brain-charting/public_analysis_code/tree/master/data_paper_scripts) (of this repo) but AFAIK this file will be deprecated soon, since a better cognitive description is already present in the column 'tags' of [all_contrasts.tsv](https://github.com/hbp-brain-charting/public_analysis_code/blob/master/ibc_data/all_contrasts.tsv). I suggest we replace in all scripts the dependency of this file by loading the tags column of all_contrasts.tsv. If so, we should either reopen this issue or create a new one.
